# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
     routing_loader:
         default_format: json
         include_format: false
     serializer:
         serialize_null: true
     view:
         failed_validation: HTTP_BAD_REQUEST
         view_response_listener:  true
         formats:
             json: true
     exception:
         enabled: true
         codes:
             Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
             Doctrine\ORM\OptimisticLockException: HTTP_CONFLICT
         messages:
             Symfony\Component\Routing\Exception\ResourceNotFoundException: true
     body_listener: true
     format_listener:
         rules:
             - { path: '^/api(?!/doc$)', priorities: ['json'], fallback_format: json, prefer_extension: false }
     zone:
        - { path: '^/api(?!/doc$)' }
     allowed_methods_listener: true
     param_fetcher_listener: force