# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
     routing_loader:
         default_format: json
         include_format: false
     serializer:
         serialize_null: true
     view:
         failed_validation: HTTP_BAD_REQUEST
         view_response_listener:  force
         formats:
             json: true
     exception:
         enabled: true
         exception_controller: 'fos_rest.exception.controller:showAction'
         codes:
             Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
             Doctrine\ORM\OptimisticLockException: HTTP_CONFLICT
         messages:
             Symfony\Component\Routing\Exception\ResourceNotFoundException: true
     format_listener:
         rules:
             - { path: '^/api/', priorities: ['json'], fallback_format: json, prefer_extension: false }
             - { path: '^/', stop: true }
     param_fetcher_listener: force
